### ISSUE TITLE
Recorder: "continue session" fails if no trials were yet saved

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#22]

**Comment by Dirskin** [comment]
Did not reproduce.
I opened a new session, and closed it without saving a single trial.
Reopened it using continue session. looks ok. Any other trigger I missed?

**Comment by drordotan** [comment]
It's still happenning. Here's the error I got:

objc[28737]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9c527cd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x125307cd8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/git/writracker/wacom_recorder/recorder.py", line 509, in check_cfg_before_exit
    self.create_dir_copy_targets()
  File "/git/writracker/wacom_recorder/recorder.py", line 788, in create_dir_copy_targets
    copyfile(self.targets_file.name, self.results_folder_path + os.sep + "Original_targets_file_copy.csv")
  File "/Users/drordotan/anaconda/envs/py3k/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/temp/2a/Original_targets_file_copy.csv' and '/temp/2a/Original_targets_file_copy.csv' are the same file

**Comment by Dirskin** [comment]
Are the steps you're doing the same as what I wrote above? 
open session -> close without writing anything -> reopen the same session
or anything different?
It seems related to #30, I can't reproduce both of them. Is it on mac or windows?
