### ISSUE TITLE
Recorder: app crash when "continue session"

### ISSUE THREAD

**Issue by drordotan** [drordotan/writracker#30]
Traceback: 
Traceback (most recent call last):
  File "/Volumes/Dror's backup/mydata/git/writracker/wacom_recorder/recorder.py", line 445, in check_cfg_before_exit
    self.create_dir_copy_targets()
  File "/Volumes/Dror's backup/mydata/git/writracker/wacom_recorder/recorder.py", line 692, in create_dir_copy_targets
    copyfile(self.targets_file.name, self.results_folder_path + os.sep + "Original_targets_file_copy.csv")
  File "/Users/drordotan/anaconda/envs/py3k/lib/python3.7/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/temp/2a/Original_targets_file_copy.csv' and '/temp/2a/Original_targets_file_copy.csv' are the same file

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by drordotan** [comment]
[Archive.zip](https://github.com/drordotan/writracker/files/4754436/Archive.zip)
This is the targets file and the session I tried to continue

**Comment by drordotan** [comment]
Can't reproduce this bug. It seems it was solved by other changes.
